### ISSUE TITLE
The configuration of appid is hard-coded.

### ISSUE THREAD

**Issue by MikeCoder** [chuanwu/Tinker#12]
You can see code from [/bot/wechat_bot.py line:68](https://github.com/chuanwu/Tinker/blob/master/bot/wechat_bot.py#L68)

Does it matter if I want to use the wechat bot for my own wechat account?

Thanks for the open-source project.

**Comment by chuanwu** [comment]
Nope.
App id here is to construct a request url. I guess this parameter is used to discriminate versions by wechat team.
Thanks for your star. PR is highly appreciated. :)

**Comment by chuanwu** [comment]
To be more clear, this appid is hard-coded by wechat instead of me.
